// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miftdiqghdoagdckwjgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZnRkaXFnaGRvYWdkY2t3amd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTM1NDIsImV4cCI6MjA2NjAyOTU0Mn0.l96g1Ovvrw_HLiwrXyaFBQpSXnrdWq7CkugSMQ_E35M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);