// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iygwgkrslsptyysdnoak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Z3dna3JzbHNwdHl5c2Rub2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzY1MjIsImV4cCI6MjA2NTY1MjUyMn0.QnrLeDmd17HADWMDFlj_0y3zpYawZG70DfYxAd3i6KE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);